baseURL = "https://silly-snyder-ff3797.netlify.app/"
languageCode = "de-DE"
title = "Mo's Blog"
theme = "bloggeri"
description = "My site description"
paginate = 4


googleAnalytics = "UA-189684436-1"


[[menu.main]]
  name = "Ãœber mich"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/MoBoodstein"
    pre = "<i class='fab fa-github'></i>"


[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/MoBd"
    pre = "<i class='fab fa-twitter'></i>"

    [[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

[params]
    author = "Moritz Lennartz"
    authorImage = "/images/Manager.jpg"

    [[menu.main]]
    name = "Kategorien"
    url = "/categories"

    [markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true




